# Generated by Django 3.1.8 on 2021-09-04 01:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=100)),
                ('middlename', models.CharField(default='NA', max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=355)),
                ('birthdate', models.DateField(default=datetime.datetime(2021, 9, 4, 9, 26, 25, 925962))),
                ('status', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('spouse_name', models.CharField(default='None', max_length=700)),
                ('spouse_occupation', models.CharField(default='None', max_length=500)),
                ('children', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Person',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='customer.person')),
                ('date_registered', models.DateField(default=datetime.datetime(2021, 9, 4, 9, 26, 25, 933961))),
                ('profile_pic', models.FileField(upload_to='')),
            ],
            options={
                'db_table': 'Customer',
            },
            bases=('customer.person',),
        ),
    ]
