# Generated by Django 3.1.8 on 2021-09-04 01:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DVD',
            fields=[
                ('sku', models.CharField(default='10101', max_length=255, primary_key=True, serialize=False)),
                ('date_registered', models.DateField(default=datetime.datetime(2021, 9, 4, 9, 26, 25, 925962))),
                ('genre', models.CharField(max_length=1000)),
                ('title', models.CharField(max_length=350)),
                ('released_date', models.DateField(default=datetime.datetime(2021, 9, 4, 9, 26, 25, 925962))),
                ('director', models.CharField(max_length=255)),
                ('price', models.FloatField(default=0.0)),
                ('items', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'DVD',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.FileField(upload_to='')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.dvd')),
            ],
            options={
                'db_table': 'Images',
            },
        ),
        migrations.CreateModel(
            name='Cast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=500)),
                ('sku', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.dvd')),
            ],
            options={
                'db_table': 'Cast',
            },
        ),
    ]
