# Generated by Django 3.1.1 on 2020-10-09 16:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20201009_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dvd',
            name='date_registered',
            field=models.DateField(default=datetime.datetime(2020, 10, 10, 0, 55, 41, 77647)),
        ),
        migrations.AlterField(
            model_name='dvd',
            name='released_date',
            field=models.DateField(default=datetime.datetime(2020, 10, 10, 0, 55, 41, 77647)),
        ),
    ]
