# Generated by Django 3.1.1 on 2020-10-11 07:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20201010_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dvd',
            name='date_registered',
            field=models.DateField(default=datetime.datetime(2020, 10, 11, 15, 55, 45, 2011)),
        ),
        migrations.AlterField(
            model_name='dvd',
            name='released_date',
            field=models.DateField(default=datetime.datetime(2020, 10, 11, 15, 55, 45, 2011)),
        ),
    ]
