# Generated by Django 3.1.1 on 2020-10-11 07:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20201011_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dvd',
            name='date_registered',
            field=models.DateField(default=datetime.datetime(2020, 10, 11, 15, 57, 54, 757432)),
        ),
        migrations.AlterField(
            model_name='dvd',
            name='released_date',
            field=models.DateField(default=datetime.datetime(2020, 10, 11, 15, 57, 54, 757432)),
        ),
    ]
